# Generated by Django 5.0.6 on 2024-05-13 04:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("header", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Содержимое")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="blogs/", verbose_name="Превью")),
                ("views_count", models.IntegerField(default=0, verbose_name="Просмотры")),
                ("created_at", models.DateField(default=datetime.date.today, verbose_name="Дата публикации")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
